name: Update Credly badges

on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with Credly badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: tony-duong.c8de242c
